DROP TABLE IF EXISTS GENRE_FILM;
DROP TABLE IF EXISTS FRIENDS;
DROP TABLE IF EXISTS LIKES;
DROP TABLE IF EXISTS GENRE;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS FILMS;
DROP TABLE IF EXISTS RATING;




CREATE TABLE IF NOT EXISTS genre(genreID int generated by default as
                        identity primary key,
                        genre varchar);

CREATE TABLE IF NOT EXISTS rating(ratingID int generated by default as
                    identity primary key,
                    rating varchar);

CREATE TABLE IF NOT EXISTS films(id int generated by default as
            identity primary key,
            name varchar,
            description varchar,
            duration int,
            releaseDate timestamp,
            ratingID int references rating(ratingID));

CREATE TABLE IF NOT EXISTS users(id int generated by default
    as identity primary key, name varchar,
    login varchar,
    email varchar,
    birthday date);

CREATE TABLE IF NOT EXISTS genre_film(film_id int references films(id),
genreID int references genre(genreID));

CREATE TABLE IF NOT EXISTS likes(id int generated by default  as identity primary key ,
filmID int references films(id),
userID int references users(id));

CREATE TABLE IF NOT EXISTS status(id int primary key , status varchar );

CREATE TABLE IF NOT EXISTS friends(id  int generated by default  as identity
                    primary key, userId int references users(id),
                    friendId int references users(id),
                    statusID int references status(id));

